apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file config/base-services.yaml convert -c -o charts/base-services
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: mongo-express
status:
  loadBalancer: {}
