apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file config/combiner.yaml convert -c -o charts/combiner
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: combiner
  name: combiner
spec:
  ports:
    - name: "12080"
      port: 12080
      targetPort: 12080
  selector:
    io.kompose.service: combiner
status:
  loadBalancer: {}
