version: '3.3'

services:

  reducer:
    environment:
      - GET_HOSTS_FROM=dns
      - USER=test
      - PROJECT=project
    image: "tdeneke/fedn-reducer:master"
    working_dir: /app/client
    command: sh -c "fedn run reducer -n reducer  --init=./config/settings-reducer.yaml"
    volumes:
      - ${PWD}/config:/app/client/config
    ports:
        - 8090:8090

